---
geometry: "left=2.5cm,right=4cm,top=2.5cm,bottom=2cm"
fontsize: "18pt"
title: "Direct Democracy in Europe"
subtitle: "Concept and Questions"
author: "Fabio Votta and Rosa Seitz"
date: "26 February 2017"
output: pdf_document
header-includes:
- \usepackage{microtype}
- \usepackage{lmodern}
- \usepackage[ngerman, english]{babel}
---

\pagenumbering{gobble}

\vspace{1cm}

This paper aims to track "Alt Right" discourse on Facebook and extract psychometric and linguistic features of their online commentary. More specifically, we identify content that aligns with Alt Right narratives in the Facebook comment sections of relevant media outlets.

As a first step, we gathered 1.3 Million Facebook comments from several Alt Right figureheads (e.g. Milo Yiannopolis, Paul Joseph Watson and others). After text cleaning procedures, we applied sentiment analysis to identify hateful comments, leaving us with a dataset of polarized commentaries. Moreover, we used topic modeling to pinpoint Alt Right related themes (for example "anti-feminism" and "anti-white racism") resulting in a text corpus in which the relevant Alt Right narratives were successfully isolated. 
 
In a last step, we collected 1.1 million Facebook comments on several media outlets (CNN, The New York Times, The Washington Post, ABC, Breitbart and Fox News) in order to compare them to our cleaned Alt Right corpus. We estimated the cosine similarity between the document term matrices to unravel the prevalence of Alt Right discourse on media outlets. We find that Alt Right narratives are mostly found on Fox News and Breitbart, but they can also be tracked on mainstream media outlets such as CNN and The Washington Post. Our results provide a first methodological attempt at classifying Alt Right content and its spread into mainstream media channels, which could be applied across different domains in the future.

This is a bullet point

1. Item 1
2. Item 2
3. Item 3
    + Item 3a
    + Item 3b
 
 
\vspace{.5cm}
