---
output: pdf_document
---

Direct democracy has been a topic of interest to political theory and empirical research for a long time. It is often asserted that direct democracy is closest to the ideal form of democracy, which is rule of the people and by the people themselves. In this light, direct democratic institutions are an often discussed remedy of the contemporary “crisis” of representative democracy which is postulated by some scholars [cf. @pogrebinschi2015]. Therefore, the causes and effects of direct democracy are of great interest to empirical research. For example, studies indicate positive effects on political efficacy [cf. @bernhardbuehlmann2014] and satisfaction with democracy [cf. @stadelmannvatter2012]. However, other authors have pointed out that direct democracy could exclude minorities and might foster inequalities in political participation [cf. @merkelritzi2017 pp. 241]. An examination of the literature shows that effects of direct democracy are sometimes heavily disputed, empirical research does not always provide conclusive evidence and many questions remain unanswered. In this context, quantitative comparative research has assigned great importance to the question of how to measure direct democracy, as empirical results could rely heavily on the way direct democracy is operationalized. In the literature, different approaches to this question can be identified, having some elements in common but diverging in many ways. 

The aim of this work is to systematically compare selected approaches to the measurement of direct democracy on the national level in a theoretical and empirical way, as well as to examine data sources on direct democratic institutions in regard to their usability for quantitative research. It has to be noted, that this paper does not aim at giving a complete overview of the literature in terms of operationalization and measurement. Instead, only a few contemporary approaches are selected and addressed more thoroughly. In many studies, direct democracy is operationalized with a single dummy variable that specifies the existence of one specific institution.^[For example a citizens’ initiative dummy as in @bernhardbuehlmann2014.] Such studies were not examined in this paper, as the focus here lies on measurements that account for the multidimensionality of direct democracy, which cannot be captured with a simple dummy variable. Furthermore, while the study of subnational direct democratic institutions is a worthwhile task, we primarily focus on national level measurements of direct democracy for the sake of a common thread across this work. As most of the indicators are derived from studies restricted to democracies, the \textit{democracy} dimension in direct democracy is neglected in most of them. This can be seen as a shortcoming, as some autocratic or semi-democratic regimes have adopted direct popular vote instruments, using them to seemingly legitimate their rule. For a first exploratory application of the constructed measures, we also assess the indices in regard to their Freedom House classification. The approaches examined theoretically and empirically are derived from different studies or datasets, namely: @gherghina2016, a subcomponent of the @dembardata, @peters2016, @fiorino2017, and @altman2017 / @coppedge2017vdata.

The following Chapter \ref{challenges} discusses some of the general challenges in measuring direct democracy as well as criteria relevant to the measurement of direct democracy (like the decisiveness or ease of initiation/approval). In Chapter \ref{data}, some of the available data sources on direct democracy are briefly examined in regard to their content and scope, as well as their usability for quantitative research (the \textit{IDEA-Database}, the \textit{“Varieties of Democracy”-Dataset}, the \textit{Database and Search Engine for Direct Democracy} and the \textit{Direct Democracy Navigator}). Afterwards, Chapter \ref{measurement} introduces some of the contemporary approaches for the measurement of direct democracy and compares them to the previously established criteria. After reconstructing some indicators from the literature, Chapter \ref{empiric} examines some of the discussed approaches empirically. Finally, the conclusion (Chapter \ref{conclusion}) gives an overview of the examined measurements and their empirical comparison and derives implications for further research.


