---
output: pdf_document
---

The aim of this work was to systematically compare selected approaches to the measurement of direct democracy theoretically and empirically, as well as to examine available data sources on direct democratic institutions in regard to their usability for quantitative research (IDEA, V-Dem, sudd Database, the Democracy Barometer and the Direct Democracy Navigator). To this end, we first identified relevant criteria captured in contemporary measurements and then examined different Databases for direct democratic institutions in relation to these dimensions. Next, contemporary approaches assessing direct democracy on the national level @gherghina2016, a subcomponent of the @dembardata, @peters2016, @fiorino2017, and @altman2017 / @coppedge2017vdata are examined in whether they cover certain criteria, like decisiveness and easiness and if so, in which way they are accounted for in the respective index aggregation. During the examination, we differentiated between approaches assessing rules in form, rules in use and measures that include a combination of both. Another crucial differentiation is the one between bottom-up and top-down mechanisms of direct democracy, which was accounted for whenever possible. 

In the empirical comparison, we found that different direct democracy measures generally overlap substantially with mostly minor differences, although it has to be noted that we only compared rules in form, rules in use, and mixed assessments within each type of measurement as this is where our focus lied. Nevertheless, some of the differences might become relevant when assessing the effects of direct democracy empirically. In general, there is no recommendation in regard to which database should be used or which measurement approach should be taken, as this relies heavily on the research question one wishes to answer. For some questions, it might be highly relevant whether direct democratic mechanisms are provided only in their top-down variants or whether bottom-up provisions exist as well, and whether these variants are used in practice. The V-Dem data provides information which is most easily accessed, with a rather extensive range of variables on rules in form, and some superficial variables for rules in use. If one is interested in more detailed information, IDEA and the Direct Democracy Navigator provide for such regarding rules in form, while sudd provides rather in depth information on actual referendums. Regarding the operationalization of direct democracy, one has to consider whether easiness and decisiveness should be accounted for as well. In regard to how these dimensions should be weighted, the discussed approaches are far from being unified, which points out an important issue needing to be assessed by further research: Which aggregation method most accurately captures the actual impact of different quorums and thresholds on rules in form and rules in use? For example, if one wishes to assess the metaphorical “Sword of Damocles” that direct democratic rules in form are said to imply, it might be highly relevant to gather information on how high/low ease of approval and initiation are.

In regard to our goal of comparing approaches in measuring direct democracy, we have some limitations that have to be addressed and discussed in regard to implications for further research. First, we chose to only examine some of the contemporary measurement approaches and data sources more thoroughly and therefore neglected others completely. Moreover, due to the scope of this work, we refrained from comparing the measurement types with each other. For example, we could have analyzed relationships between rules in use and rules in form, as Figure \ref{heatmap} in the appendix implies that overall there isn’t a very strong correlation between them. Another possibly interesting approach would have been to conduct a factor analysis with the derived variables, to assess whether the dimensions bottom-up, top-down or rules in use and rules in form are actually present in the data, or whether specific measurements have other underlying dimensions. All of these limitations can at the same time be understood as recommendations for future research. Moreover, our study did not discuss how to aggregate direct popular vote  into direct *democracy* measurements, when assessing a broader scope of countries including autocracies, which is also a topic worthy of further discussion. In this context, it could also be interesting to group top-down or bottom-up measures per regime type, as it would be plausible to expect different distributions between autocracies and democracies. A limitation of this study, but also one of many contemporary measurement approaches, is the neglection of two important factors: subnational democracy and the content and scope of issues for which direct democratic mechanisms are allowed/excluded, mostly because their assessment is an even more difficult task than the one of easiness or decisiveness. An important recommendation for further research is to arrive at a more unified, but also detailed scheme of classifying direct democracy institutions, as well as a common terminology as to ensure comparability and reproducibility between different kinds of research.
